# Generated by Django 3.0.6 on 2020-05-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='about',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fax',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtppassword',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpserver',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]